### ISSUE TITLE
"from liftover import get_lifter" from first line of documentation doesn't work

### ISSUE THREAD

**Issue by ahstram** [jeremymcrae/liftover#5]
Trying to run the example in your "Usage" section of documentation, script fails on the first line:

```
$ pip3 freeze | grep liftover
liftover==1.1.10
```

```
$ cat liftover.py
#!/usr/bin/env python3
from liftover import get_lifter
```

error:

```
$ ./liftover.py
Traceback (most recent call last):
  File "./liftover.py", line 3, in <module>
    from liftover import get_lifter
  File "./liftover.py", line 3, in <module>
    from liftover import get_lifter
ImportError: cannot import name 'get_lifter'
```

**Comment by ahstram** [comment]
Disregard, issue was due to naming the test script "liftover.py", which conflicts with the module name. My test script was trying to import itself :/
